version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    depends_on:
      - backend
    build: ./nginx/
    env_file: .env
    ports:
      - 10000:80
    volumes:
      - ./frontend/build/:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
