##############################
###    COMMON VARIABLES    ###
##############################
@contentType = application/json
@email = email@email.ru
@username = vasya
@password = lili5555
@vasyaToken = Token 1ffc39a8ddd151fe8a616bc0369546224be38405
@anotherVasyaToken = Token 4bfa3e8667a02f738032b503b47b0692e52d3933


##############################
### SOME OF USERS REQUESTS ###
##############################

### anonim GET user list 200 results empty
GET http://127.0.0.1:8000/api/users/

### vasya GET user list 200 results self.user
GET http://127.0.0.1:8000/api/users/
Authorization: {{vasyaToken}}

### vasya GET user limit 200 results self.user
GET http://127.0.0.1:8000/api/users/?limit=1
Authorization: {{vasyaToken}}

### anonim GET user profile 200 empty
GET http://127.0.0.1:8000/api/users/1/

### vasya GET user profile 200 results self.user
GET http://127.0.0.1:8000/api/users/4/
Authorization: {{vasyaToken}}

### anotherVasya GET user profile 200 results self.user
GET http://127.0.0.1:8000/api/users/1/
Authorization: {{anotherVasyaToken}}

### anonim GET users/me/ 401
GET http://127.0.0.1:8000/api/users/me/

### vasya GET users/me/ 200 results self.user
GET http://127.0.0.1:8000/api/users/me/
Authorization: {{vasyaToken}}



##############################
### SOME OF TOKEN REQUESTS ###
##############################

### anonim CREATE USER 200 if user does not exist
POST http://127.0.0.1:8000/api/users/
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "username": "{{username}}",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "{{password}}"
}

### anonim GET TOKEN for existing user 201
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### user DESTROY TOKEN 204
POST http://127.0.0.1:8000/api/auth/token/logout/


### anonim CREATE USER WITH BAD USERNAME 400
POST http://127.0.0.1:8000/api/users/
Content-Type: {{contentType}}

{
    "username": "InvalidU$ername",
    "email": "invalid-username@user.ru",
    "first_name": "Invalid",
    "last_name": "Username",
    "password": "{{password}}"
}


#############################
### SOME OF TAGS REQUESTS ###
#############################

### anonim GET tags 200
GET http://127.0.0.1:8000/api/tags/

### anonim POST tags 405
POST http://127.0.0.1:8000/api/tags/

{
    "name": "Завтрак",
    "color": "#E26CFD",
    "slug": "breakfast"
}


###################################
### SOME OF INGREDIENT REQUESTS ###
###################################

### anonim GET ingredients 200
GET http://127.0.0.1:8000/api/ingredients/


################################
### SOME OF RECIPES REQUESTS ###
################################

### anonim GET recipes 200
GET http://127.0.0.1:8000/api/recipes/

### vasya GET recipes limit 200
GET http://127.0.0.1:8000/api/recipes/?limit=1
Authorization: {{vasyaToken}}

### vasya GET recipes filter 200
GET http://127.0.0.1:8000/api/recipes/?tags=obed
Authorization: {{vasyaToken}}

### vasya GET recipe 200
GET http://127.0.0.1:8000/api/recipes/108
Authorization: {{vasyaToken}}

### vasya POST users/recipes/ 201
PATCH http://127.0.0.1:8000/api/recipes/
Authorization: {{vasyaToken}}
Content-Type: {{contentType}}

{
    "ingredients": [
        {
            "id": 1,
            "amount": 10
        },
        {
            "id": 2,
            "amount": 20
        }
    ],
    "tags": [
        1,
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "Нечто съедобное (это не точно)",
    "text": "Приготовьте как нибудь эти ингредиеты",
    "cooking_time": 5
}

### anotherVasya POST users/recipes/ 201
PATCH http://127.0.0.1:8000/api/recipes/119/
Authorization: {{anotherVasyaToken}}
Content-Type: {{contentType}}

{
    "ingredients": [
        {
            "id": 1,
            "amount": 25
        }
    ],
    "tags": [
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "Нечто съедобное (пробовать на свой страх и риск)",
    "text": "Приготовьте как нибудь эти ингредиеты, не забудьте посолить.",
    "cooking_time": 12
}