# Generated by Django 3.2.3 on 2023-11-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20231127_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='amount',
        ),
    ]
