# Generated by Django 3.2.3 on 2023-11-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_unit',
        ),
    ]
