# Generated by Django 3.2.3 on 2023-11-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcat',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='achievementcat',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='achievements',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='AchievementCat',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
