# Generated by Django 3.2.3 on 2023-11-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20231127_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
