# Generated by Django 3.2.3 on 2023-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=10, verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
    ]
