# Generated by Django 3.2.3 on 2023-11-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
