# Generated by Django 3.2.3 on 2023-11-20 04:21

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, validators=[users.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
